name: KS Pipeline

on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: 'Solution Name'
        required: true
        type: string

permissions:
  contents: write

jobs:
  export-solution:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Power Platform CLI
        uses: microsoft/powerplatform-actions/actions-install@v1

      - name: Authenticate to Dataverse
        run: |
          $POWERPLATFORMTOOLS_PACPATH auth create \
            --applicationId "${{ secrets.POWERPLATFORM_APP_ID }}" \
            --clientSecret "${{ secrets.POWERPLATFORM_CLIENT_SECRET }}" \
            --tenant "${{ secrets.POWERPLATFORM_TENANT_ID }}" \
            --environment "${{ secrets.DEV_ENV_URL }}"

      - name: Export Unmanaged Solution
        run: |
         $POWERPLATFORMTOOLS_PACPATH solution export \
            --name "${{ github.event.inputs.solution_name }}" \
            --path "${{ github.event.inputs.solution_name }}.zip" \
            --managed false

      - name: Export Managed Solution
        run: |
         $POWERPLATFORMTOOLS_PACPATH solution export \
            --name "${{ github.event.inputs.solution_name }}" \
            --path "${{ github.event.inputs.solution_name }}_managed.zip" \
            --managed true

      - name: Create Folders
        run: |
          rm -rf Artifacts/Solutions/Managed/${{ github.event.inputs.solution_name }}
          rm -rf Artifacts/Solutions/Unmanaged/${{ github.event.inputs.solution_name }}

          mkdir -p Artifacts/Solutions/Managed/${{ github.event.inputs.solution_name }}
          mkdir -p Artifacts/Solutions/Unmanaged/${{ github.event.inputs.solution_name }}

      - name: Commit Changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add Artifacts/

          git commit -m "Export ${{ github.event.inputs.solution_name }} managed and unmanaged solutions" || echo "No changes detected"

          git push origin develop

      - name: Clear Authentication
        run: |
          $POWERPLATFORMTOOLS_PACPATH auth clear
